<?php
    $settings = $template?->settings ?? [];
    $primary = $settings['primary_color'] ?? '#0f766e';
    $logoRelative = $publication->school->logo_path;
    $signatureRelative = $publication->school->principal_signature_path;
    $logo = $logoRelative && is_file(storage_path('app/public/'.$logoRelative)) ? storage_path('app/public/'.$logoRelative) : null;
    $signature = $signatureRelative && is_file(storage_path('app/public/'.$signatureRelative)) ? storage_path('app/public/'.$signatureRelative) : null;
?>
<!doctype html>
<html>
<head><meta charset="utf-8"><style>
@page{margin:22px}body{font-family:DejaVu Sans,sans-serif;color:#18303f;font-size:9px}.card{page-break-after:always}.card:last-child{page-break-after:auto}.header{border:2px solid <?php echo e($primary); ?>;padding:10px;text-align:center;position:relative}.logo{position:absolute;left:12px;top:9px;width:55px;height:55px;object-fit:contain}.header h1{margin:0 65px 4px;font-size:19px;color:<?php echo e($primary); ?>}.title{background:<?php echo e($primary); ?>;color:#fff;text-align:center;padding:6px;font-weight:bold;margin:7px 0}.info,.results,.summary,.comments,.approvals{width:100%;border-collapse:collapse}.info td,.results th,.results td,.comments td{border:1px solid #bfcdd4;padding:5px}.results th{background:#e9f3f1}.center{text-align:center}.summary{margin-top:7px}.summary td{text-align:center;background:#edf4f5;padding:6px;border:3px solid #fff}.comments{margin-top:8px}.comments td{width:50%;height:45px;vertical-align:top}.approvals{margin-top:15px}.approvals td{width:50%;text-align:center;padding:0 45px}.line{border-top:1px solid #718894;padding-top:3px}.signature{height:30px;max-width:110px}.small{font-size:7px;margin-top:6px}
</style></head>
<body>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $summaries; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $summary): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?>
<?php $snapshot=$summary->snapshot; $subjects=$snapshot['subjects']??[]; $sum=$snapshot['summary']??[]; ?>
<div class="card">
<div class="header"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($logo): ?><img class="logo" src="<?php echo e($logo); ?>"><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?><h1><?php echo e(data_get($snapshot,'school.name')); ?></h1><div><?php echo e(data_get($snapshot,'school.address')); ?></div><em><?php echo e(data_get($snapshot,'school.motto')); ?></em></div>
<div class="title"><?php echo e($settings['header_note'] ?? 'TERMINAL ACADEMIC REPORT'); ?></div>
<table class="info"><tr><td><b>Student:</b> <?php echo e(data_get($snapshot,'student.name')); ?></td><td><b>Admission:</b> <?php echo e(data_get($snapshot,'student.admission_number')); ?></td><td><b>Class:</b> <?php echo e(data_get($snapshot,'academic.class')); ?></td></tr><tr><td><b>Session:</b> <?php echo e(data_get($snapshot,'academic.session')); ?></td><td><b>Term:</b> <?php echo e(data_get($snapshot,'academic.term')); ?></td><td><b>Gender:</b> <?php echo e(ucfirst(data_get($snapshot,'student.gender','—'))); ?></td></tr></table>
<table class="results"><thead><tr><th>Subject</th><th>CA</th><th>Exam</th><th>Total</th><th>Grade</th><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($settings['show_subject_position']??true): ?><th>Position</th><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?><th>Remark</th></tr></thead><tbody><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $subjects; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $row): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><tr><td><?php echo e($row['subject']); ?></td><td class="center"><?php echo e($row['ca_score']??'—'); ?></td><td class="center"><?php echo e($row['exam_score']??'—'); ?></td><td class="center"><?php echo e($row['total_score']??'—'); ?></td><td class="center"><b><?php echo e($row['grade']); ?></b></td><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($settings['show_subject_position']??true): ?><td class="center"><?php echo e($row['position']??'—'); ?></td><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?><td><?php echo e($row['remark']); ?></td></tr><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></tbody></table>
<table class="summary"><tr><td>Total<br><b><?php echo e(number_format((float)($sum['total_score']??0),2)); ?></b></td><td>Average<br><b><?php echo e(number_format((float)($sum['average_score']??0),2)); ?>%</b></td><td>Position<br><b><?php echo e($sum['class_position']??'—'); ?></b></td><td>Class size<br><b><?php echo e($sum['class_size']??'—'); ?></b></td><td>Subjects<br><b><?php echo e($sum['subject_count']??count($subjects)); ?></b></td></tr></table>
<table class="comments"><tr><td><b>Class teacher's comment</b><br><br><?php echo e($summary->teacher_comment?:'—'); ?></td><td><b>Principal's comment</b><br><br><?php echo e($summary->principal_comment?:'—'); ?></td></tr></table>
<table class="approvals"><tr><td><div class="line">Class Teacher</div></td><td><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($signature): ?><img class="signature" src="<?php echo e($signature); ?>"><br><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?><div class="line"><?php echo e(data_get($snapshot,'school.principal_name') ?: 'Principal'); ?></div></td></tr></table>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(data_get($snapshot,'next_term_begins_on')): ?><div class="small"><b>Next term begins:</b> <?php echo e(\Carbon\Carbon::parse(data_get($snapshot,'next_term_begins_on'))->format('d F Y')); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($settings['show_grading_scale']??true): ?><div class="small"><b>Grading scale:</b> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = ($snapshot['grading_scale']??[]); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $band): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?> <?php echo e($band['grade']); ?> (<?php echo e($band['min']); ?>+) <?php echo e($band['remark']); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!$loop->last): ?> | <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<div class="small">Result version <?php echo e($publication->version); ?> · <?php echo e(strtoupper($publication->status->value)); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($settings['show_verification_code']??true): ?> · Verification code <?php echo e(strtoupper(substr(str_replace('-','',$summary->public_token),0,16))); ?><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div>
</div>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
</body></html>
<?php /**PATH /Users/buhafran/Downloads/ResultSystem-2/backend/resources/views/result/pdf/class-report-cards.blade.php ENDPATH**/ ?>